title: "jkoby - Hacker, writer, consultant, etc."
description: "Writings, ramblings, and various notes."
show_downloads: false
remote_theme: "dracula/gh-pages"
show_header: true

sass:
    style: compressed

theme: jekyll-theme-hacker